---
- hosts: rzd
  gather_facts: no
  become: yes
  tasks:
  - name: Copy client/
    copy:
      src: ../client/
      dest: /opt/client

  - name: Copy cicd
    copy:
      src: ../cicd/
      dest: /opt/cicd

  - name: Install docker module
    pip:
      name: [docker, docker-compose]
      
  - name: Build new image
    docker_compose:
      project_src: /opt/cicd
      state: present
      build: yes
    register: output

  - name: Restart
    docker_compose:
      project_src: /opt/cicd
      services:
        - —Ålient
      state: present
      restarted: true
    register: output

  - debug:
      var: output
