version: '2.4'

services:
  core:
    build:
      context: ../server
      target: server
    ports:
      - "8080:8080"
    volumes:
      - ../data:/mnt/server
    working_dir: /mnt/

  client:
    build:
      context: ../client
    ports:
      - "4200:4200"
    volumes:
      - ../client/cp-frontend:/app
      - /app/node_modules