version: '2.4'

services:
  core:
    build:
      context: ../server
      target: server
    command: /bin/bash -c 'alembic upgrade head && python3 manage.py'
    ports:
      - "8080:8080"
    volumes:
      - ../data:/mnt/data
      - /home/svc_k806/.postgresql/root.crt:/root/.postgresql/root.crt
    working_dir: /mnt/
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_ENV: prod

  client:
    build:
      context: ../client
    ports:
      - "4200:4200"
    volumes:
      - ../client/cp-frontend:/app
      - /app/node_modules