version: '2.4'

services:
  core:
    build:
      context: ../server
      target: server
    ports:
      - "8080:8080"
    volumes:
      - ../server:/mnt
    working_dir: /mnt/
    environment:
      - PYTHONDONTWRITEBYTECODE=1

  client:
    build:
      context: ../client
    ports:
      - "4200:4200"
    volumes:
      - ../client/cp-frontend:/app
      - /app/node_modules
