---
- hosts: rzd
  gather_facts: no
  become: yes
  tasks:
  - name: Copy server/
    copy:
      src: ../server/
      dest: /opt/server

  - name: Copy cicd
    copy:
      src: ../cicd/
      dest: /opt/cicd

  - name: Install docker module
    pip:
      name: [docker, docker-compose]
      
  - name: Restart
    docker_compose:
      project_src: /opt/cicd
      services:
        - core
      state: present
      restarted: true
    register: output

  - debug:
      var: output
