- name: Run playbook
  uses: dawidd6/action-ansible-playbook@v2
  with:
    playbook: server-deploy.yml
    directory: ./cicd
    key: ${{secrets.ANSIBLE_SSH_KEY}}
    inventory: |
      [rzd]
      178.154.229.242 ansible_user=svc_k806
    options: |
      -u svc_k806
      -vvv